# Configurations
title:            《台灣俗語鹹酸甜》第1冊
longtitle:        Tâi-oân Sio̍k-gí Kiâm-sng-tiⁿ (台灣俗語鹹酸甜)
author:           Siau Lah-jih
email:            
description: >
  Tâi-oân Sio̍k-gí Kiâm-sng-tiⁿ《台灣俗語鹹酸甜》第1冊

version:          2.0
gitbook_version:  3.2.3

url:              'https://siaulahjih.github.io'
baseurl:          '/KiamsngtinnKangteng'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: false
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
  typographic_symbols:
    ndash: --

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:month-:day:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - posts

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

tracker:
  google_analytics: "G-XG4HSSM1PZ"

extra_css: extra_css.css
extra_header_js: extra_header_js.js
extra_footer_js: extra_footer_js.js
